version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: yad2_crm_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-yad2_crm}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
